"""add tabela users

Revision ID: 3fdfe1a91380
Revises: f4caec97700b
Create Date: 2024-09-25 22:50:33.312632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdfe1a91380'
down_revision: Union[str, None] = 'f4caec97700b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('senha', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.add_column('transacoes', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transacoes', 'usuarios', ['usuario_id'], ['id'])

    op.add_column('categorias', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categorias', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias', type_='foreignkey')
    op.drop_column('categorias', 'usuario_id')

    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_column('transacoes', 'usuario_id')

    op.drop_table('usuarios')
    # ### end Alembic commands ###
